version: "3.8"

services:
  unifi-db:
#    image: mongo:7.0.10-rc0-jammy
    image: mongo:4.4.9-rc0-focal
    container_name: unifi-db
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
          
  unifi-network-application:
    image: linuxserver/unifi-network-application:9.0.108-ls76
    container_name: unifi-network-application
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Argentina/Buenos_Aires
      - MONGO_USER=MONGO_USER2
      - MONGO_PASS=MONGO_PASS2
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=MONGO_DBNAME2
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - ./unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
